### ISSUE TITLE
Will there be the experiment codes for the real world data?

### ISSUE THREAD

**Issue by LenarBe** [andreacini/sparse-graph-learning#2]
Hi andreacini! Thank you for your extraordinary work but I have some questions. As I see in 'Multivariate Time Series Forecasting with Latent Graph Inference' it has no open-source official code, so I wonder if there will be yours in this project, because my naive implementation from the description performs not as well as I wanted. 

I think it's because the 'encoder' part uses MLP and drops the temporal dependencies of the data. However, I don't know how to modify this part. Thanks a lot if you can give me some advice!

**Comment by andreacini** [comment]
Hi, I recommend directing any questions about that paper to its authors, as they are better suited to answer. However, we were able to implement their model and achieve good results as reported in the paper.
